# Generated by Django 2.2 on 2024-09-30 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_userprofilefeeditem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfileFeedItem',
        ),
    ]
